[mypy]
# Exclude the virtual environment folder
exclude = ^(test|venv|\.venv)/

# Mandatory flags from Chapter III.2
warn_return_any = True
warn_unused_ignores = True
ignore_missing_imports = True
disallow_untyped_defs = True
check_untyped_defs = True

# Ensure errors are easy to read during review
show_error_codes = True
pretty = True
